// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskManagementSystem.Repository.Models;

public partial class Attachment
{
    public int AttachmentId { get; set; }

    public int TaskId { get; set; }

    public string FileName { get; set; }

    public string FilePath { get; set; }

    public int? UploadedBy { get; set; }

    public DateTime? UploadedDate { get; set; }

    public virtual ProjectTask Task { get; set; }

    public virtual SystemUserAccount UploadedByNavigation { get; set; }
}