// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskManagementSystem.Repository.Models;

public partial class AuditLog
{
    public int AuditLogId { get; set; }

    public int? UserId { get; set; }

    public string TableName { get; set; }

    public int? RecordId { get; set; }

    public string Action { get; set; }

    public string OldValue { get; set; }

    public string NewValue { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual SystemUserAccount User { get; set; }
}