// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskManagementSystem.Repository.Models;

public partial class Comment
{
    public int CommentId { get; set; }

    public int TaskId { get; set; }

    public int UserId { get; set; }

    public string Content { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual ProjectTask Task { get; set; }

    public virtual SystemUserAccount User { get; set; }
}