// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskManagementSystem.Repository.Models;

public partial class ProjectTask
{
    public int TaskId { get; set; }

    public int ProjectId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public byte? Priority { get; set; }

    public byte? Status { get; set; }

    public DateOnly? DueDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual ICollection<Attachment> Attachments { get; set; } = new List<Attachment>();

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual SystemUserAccount CreatedByNavigation { get; set; }

    public virtual Project Project { get; set; }

    public virtual ICollection<TaskAssignment> TaskAssignments { get; set; } = new List<TaskAssignment>();

    public virtual ICollection<TaskHistory> TaskHistories { get; set; } = new List<TaskHistory>();
}