// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskManagementSystem.Repository.Models;

public partial class ProjectMember
{
    public int ProjectMemberId { get; set; }

    public int ProjectId { get; set; }

    public int UserId { get; set; }

    public DateTime? JoinedDate { get; set; }

    public virtual Project Project { get; set; }

    public virtual SystemUserAccount User { get; set; }
}