// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskManagementSystem.Repository.Models;

public partial class TaskHistory
{
    public int TaskHistoryId { get; set; }

    public int? TaskId { get; set; }

    public byte? OldStatus { get; set; }

    public byte? NewStatus { get; set; }

    public int? ChangedBy { get; set; }

    public DateTime? ChangedDate { get; set; }

    public virtual SystemUserAccount ChangedByNavigation { get; set; }

    public virtual ProjectTask Task { get; set; }
}