// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskManagementSystem.Repository.Models;

public partial class TaskAssignment
{
    public int TaskAssignmentId { get; set; }

    public int TaskId { get; set; }

    public int UserId { get; set; }

    public DateTime? AssignedDate { get; set; }

    public virtual ProjectTask Task { get; set; }

    public virtual SystemUserAccount User { get; set; }
}